import GithubSlugger from "github-slugger";
import type { ReaderTocEntry } from "@/lib/content/types";

// Pure text transforms that turn a set of lesson MDX bodies into one combined
// reader document plus its numbered section tree. No filesystem access — the
// caller (scripts/build-readers.ts and the freshness test) supplies raw MDX.
//
// Rules, per lesson:
//   1. Its own headings are shifted so the shallowest becomes `##` (level 2),
//      keeping the lesson's internal nesting but leaving `#` for the title.
//   2. Manual "N." section numbers baked into headings (e.g. "## 2. Setting")
//      are stripped — the reader generates its own numbers.
//   3. The lesson title is prepended as a `#` (level-1) section.
// Concatenating and compiling as ONE MDX document is what keeps every heading's
// rehype-slug anchor id unique across lessons.

const FENCE = /^\s{0,3}(```|~~~)/;
const HEADING = /^(#{1,6})\s+(.*)$/;
// A leading "2." / "3.1." style number (requires the trailing dot so ordinary
// numeric prose like "2024 trends" is left alone).
const MANUAL_NUMBER = /^\d+(?:\.\d+)*\.\s+/;

interface RawHeading {
  index: number;
  level: number;
  text: string;
}

function scanHeadings(lines: string[]): RawHeading[] {
  const out: RawHeading[] = [];
  let inFence = false;
  for (let i = 0; i < lines.length; i++) {
    if (FENCE.test(lines[i])) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    const m = HEADING.exec(lines[i]);
    if (m) out.push({ index: i, level: m[1].length, text: m[2].trim() });
  }
  return out;
}

/** Transform one lesson body into a `#`-titled section of the reader. */
export function transformLessonToSection(title: string, raw: string): string {
  const lines = raw.replace(/\r\n/g, "\n").split("\n");
  const headings = scanHeadings(lines);
  const minLevel = headings.length
    ? Math.min(...headings.map((h) => h.level))
    : 2;
  const shift = 2 - minLevel;

  for (const h of headings) {
    const level = Math.min(6, Math.max(2, h.level + shift));
    const text = h.text.replace(MANUAL_NUMBER, "");
    lines[h.index] = `${"#".repeat(level)} ${text}`;
  }

  const body = lines.join("\n").trim();
  return `# ${title}\n\n${body}`;
}

const GENERATED_BANNER =
  "{/* GENERATED by scripts/build-readers.ts — do not edit by hand. Run `npm run readers:build`. */}";

/** Join transformed sections into the final reader MDX document. */
export function assembleReaderMdx(sections: string[]): string {
  const body = sections.map((s) => s.trim()).join("\n\n");
  return `${GENERATED_BANNER}\n\n${body}\n`;
}

/**
 * Build the numbered section tree from a combined reader MDX. Numbers are
 * assigned per heading level (level 1 = lesson title = "1", "2", …; each deeper
 * level nests below), and ids use the same github-slugger rehype-slug uses, in
 * document order, so anchors line up with the rendered page.
 */
export function buildReaderToc(mdx: string): ReaderTocEntry[] {
  const slugger = new GithubSlugger();
  const counters = [0, 0, 0, 0, 0, 0, 0];
  const toc: ReaderTocEntry[] = [];
  let inFence = false;
  for (const line of mdx.split("\n")) {
    if (FENCE.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    const m = HEADING.exec(line);
    if (!m) continue;
    const level = m[1].length;
    const title = m[2].trim();
    counters[level] += 1;
    for (let k = level + 1; k < counters.length; k++) counters[k] = 0;
    toc.push({
      id: slugger.slug(title),
      title,
      number: counters.slice(1, level + 1).join("."),
      level,
    });
  }
  return toc;
}
