// GENERATED by scripts/build-readers.ts — do not edit by hand.
// Run `npm run readers:build` to regenerate.
import type { ReaderTocEntry } from "@/lib/content/types";

export const readerTocs: Record<string, ReaderTocEntry[]> = {
  "c-reader-demo": [
  {
    "id": "trusted-monitoring-as-a-game",
    "title": "Trusted monitoring as a game",
    "number": "1",
    "level": 1
  },
  {
    "id": "same-auroc-different-safety",
    "title": "Same AUROC, different safety",
    "number": "2",
    "level": 1
  },
  {
    "id": "safety-over-a-deployment-the-race",
    "title": "Safety over a deployment: the race",
    "number": "3",
    "level": 1
  },
  {
    "id": "opportunities-are-not-equal",
    "title": "Opportunities are not equal",
    "number": "4",
    "level": 1
  },
  {
    "id": "subtlety-visible-versus-reliable",
    "title": "Subtlety: visible versus reliable",
    "number": "5",
    "level": 1
  },
  {
    "id": "the-best-response-principle",
    "title": "The best-response principle",
    "number": "6",
    "level": 1
  },
  {
    "id": "defer-to-trusted-mechanistically",
    "title": "Defer to trusted, mechanistically",
    "number": "7",
    "level": 1
  },
  {
    "id": "the-control-game-the-whole-picture",
    "title": "The control game: the whole picture",
    "number": "8",
    "level": 1
  }
],
};
