// GENERATED by scripts/build-readers.ts — do not edit by hand.
// Run `npm run readers:build` to regenerate.
import type { ReaderTocEntry } from "@/lib/content/types";

export const readerTocs: Record<string, ReaderTocEntry[]> = {
  "c-reader-paper": [
  {
    "id": "abstract--introduction",
    "title": "Abstract & Introduction",
    "number": "1",
    "level": 1
  },
  {
    "id": "abstract",
    "title": "Abstract",
    "number": "1.1",
    "level": 2
  },
  {
    "id": "introduction",
    "title": "Introduction",
    "number": "1.2",
    "level": 2
  },
  {
    "id": "setting",
    "title": "Setting",
    "number": "2",
    "level": 1
  },
  {
    "id": "setting-1",
    "title": "Setting",
    "number": "2.1",
    "level": 2
  },
  {
    "id": "the-red-team-provides-a-secret-pipeline-for-the-attack-policy",
    "title": "The Red Team Provides a Secret Pipeline for the Attack Policy",
    "number": "2.1.1",
    "level": 3
  },
  {
    "id": "limited-access-to-high-quality-labor",
    "title": "Limited Access to High-quality Labor",
    "number": "2.1.2",
    "level": 3
  },
  {
    "id": "blue-team-access-to-summary-statistics-of-original-gpt-4s-performance",
    "title": "Blue Team Access to Summary Statistics of Original GPT-4's Performance",
    "number": "2.1.3",
    "level": 3
  },
  {
    "id": "miscellaneous-other-simplifications-and-assumptions",
    "title": "Miscellaneous Other Simplifications and Assumptions",
    "number": "2.1.4",
    "level": 3
  },
  {
    "id": "approximating-large-games-with-low-variance-and-limited-api-usage",
    "title": "Approximating Large Games With Low Variance and Limited API Usage",
    "number": "2.1.5",
    "level": 3
  },
  {
    "id": "results-i--baselines--trusted-monitoring",
    "title": "Results I — Baselines & Trusted Monitoring",
    "number": "3",
    "level": 1
  },
  {
    "id": "results",
    "title": "Results",
    "number": "3.1",
    "level": 2
  },
  {
    "id": "baseline-results",
    "title": "Baseline Results",
    "number": "3.1.1",
    "level": 3
  },
  {
    "id": "avoid-using-untrusted-models",
    "title": "Avoid Using Untrusted Models",
    "number": "3.1.1.1",
    "level": 4
  },
  {
    "id": "upfront-auditing",
    "title": "Upfront Auditing",
    "number": "3.1.1.2",
    "level": 4
  },
  {
    "id": "trusted-monitoring",
    "title": "Trusted Monitoring",
    "number": "3.1.2",
    "level": 3
  },
  {
    "id": "qualitative-analysis",
    "title": "Qualitative Analysis",
    "number": "3.1.2.1",
    "level": 4
  },
  {
    "id": "extending-trusted-monitoring-with-untrusted-justification",
    "title": "Extending Trusted Monitoring With Untrusted Justification",
    "number": "3.1.2.2",
    "level": 4
  },
  {
    "id": "results-ii--defer-to-trusted-untrusted-monitoring--trusted-editing",
    "title": "Results II — Defer to Trusted, Untrusted Monitoring & Trusted Editing",
    "number": "4",
    "level": 1
  },
  {
    "id": "defer-to-trusted",
    "title": "Defer to Trusted",
    "number": "4.1",
    "level": 2
  },
  {
    "id": "untrusted-monitoring",
    "title": "Untrusted Monitoring",
    "number": "4.2",
    "level": 2
  },
  {
    "id": "making-it-difficult-to-distinguish-synthetic-and-real-inputs",
    "title": "Making It Difficult to Distinguish Synthetic and Real Inputs",
    "number": "4.2.1",
    "level": 3
  },
  {
    "id": "collusion-techniques-and-countermeasures",
    "title": "Collusion Techniques and Countermeasures",
    "number": "4.2.2",
    "level": 3
  },
  {
    "id": "defer-to-trusted-1",
    "title": "Defer to Trusted",
    "number": "4.2.3",
    "level": 3
  },
  {
    "id": "trusted-editing",
    "title": "Trusted Editing",
    "number": "4.3",
    "level": 2
  },
  {
    "id": "comments-on-these-experimental-results",
    "title": "Comments on These Experimental Results",
    "number": "4.4",
    "level": 2
  },
  {
    "id": "discussion",
    "title": "Discussion",
    "number": "5",
    "level": 1
  },
  {
    "id": "discussion-1",
    "title": "Discussion",
    "number": "5.1",
    "level": 2
  },
  {
    "id": "difficulties-and-limitations-of-ai-control",
    "title": "Difficulties and Limitations of AI Control",
    "number": "5.1.1",
    "level": 3
  },
  {
    "id": "difficulties-with-using-control-evaluations-in-practice",
    "title": "Difficulties With Using Control Evaluations in Practice",
    "number": "5.1.1.1",
    "level": 4
  },
  {
    "id": "difficulties-with-scaling-control-techniques",
    "title": "Difficulties With Scaling Control Techniques",
    "number": "5.1.1.2",
    "level": 4
  },
  {
    "id": "why-we-didnt-consider-strategies-that-involve-training-the-model",
    "title": "Why We Didn't Consider Strategies That Involve Training the Model",
    "number": "5.1.2",
    "level": 3
  },
  {
    "id": "glossary",
    "title": "Glossary",
    "number": "6",
    "level": 1
  },
  {
    "id": "appendix-a-glossary",
    "title": "Appendix A. Glossary",
    "number": "6.1",
    "level": 2
  },
  {
    "id": "justification-of-summary-statistics-access",
    "title": "Justification of Summary Statistics Access",
    "number": "7",
    "level": 1
  },
  {
    "id": "appendix-b-justification-of-the-blue-team-access-to-summary-statistics",
    "title": "Appendix B. Justification of the Blue Team Access to Summary Statistics",
    "number": "7.1",
    "level": 2
  },
  {
    "id": "summary-statistics-when-using-control-evaluations-to-assess-the-safety-of-an-actual-protocol-used-for-dangerous-models",
    "title": "Summary Statistics When Using Control Evaluations to Assess the Safety of an Actual Protocol Used for Dangerous Models",
    "number": "7.1.1",
    "level": 3
  },
  {
    "id": "summary-statistics-for-current-technique-development",
    "title": "Summary Statistics for Current Technique Development",
    "number": "7.1.2",
    "level": 3
  },
  {
    "id": "the-black-box-protocol-assumption",
    "title": "The Black-Box Protocol Assumption",
    "number": "8",
    "level": 1
  },
  {
    "id": "appendix-c-the-black-box-protocol-assumption",
    "title": "Appendix C. The Black-Box Protocol Assumption",
    "number": "8.1",
    "level": 2
  },
  {
    "id": "white-box-techniques",
    "title": "White-box techniques",
    "number": "8.1.1",
    "level": 3
  }
],
  "c-reader-demo": [
  {
    "id": "why-a-good-monitor-still-misses",
    "title": "Why a good monitor still misses",
    "number": "1",
    "level": 1
  },
  {
    "id": "trusted-monitoring-as-a-game",
    "title": "Trusted monitoring as a game",
    "number": "1.1",
    "level": 2
  },
  {
    "id": "same-auroc-different-safety",
    "title": "Same AUROC, different safety",
    "number": "2",
    "level": 1
  },
  {
    "id": "same-auroc-different-safety-1",
    "title": "Same AUROC, different safety",
    "number": "2.1",
    "level": 2
  },
  {
    "id": "safety-over-a-deployment-the-race",
    "title": "Safety over a deployment: the race",
    "number": "3",
    "level": 1
  },
  {
    "id": "safety-over-a-deployment-the-race-1",
    "title": "Safety over a deployment: the race",
    "number": "3.1",
    "level": 2
  },
  {
    "id": "opportunities-are-not-equal",
    "title": "Opportunities are not equal",
    "number": "4",
    "level": 1
  },
  {
    "id": "opportunities-are-not-equal-1",
    "title": "Opportunities are not equal",
    "number": "4.1",
    "level": 2
  },
  {
    "id": "subtlety-visible-versus-reliable",
    "title": "Subtlety: visible versus reliable",
    "number": "5",
    "level": 1
  },
  {
    "id": "subtlety-visible-versus-reliable-1",
    "title": "Subtlety: visible versus reliable",
    "number": "5.1",
    "level": 2
  },
  {
    "id": "the-best-response-principle",
    "title": "The best-response principle",
    "number": "6",
    "level": 1
  },
  {
    "id": "the-best-response-principle-1",
    "title": "The best-response principle",
    "number": "6.1",
    "level": 2
  },
  {
    "id": "defer-to-trusted-mechanistically",
    "title": "Defer to trusted, mechanistically",
    "number": "7",
    "level": 1
  },
  {
    "id": "defer-to-trusted-mechanistically-1",
    "title": "Defer to trusted, mechanistically",
    "number": "7.1",
    "level": 2
  },
  {
    "id": "the-control-game-the-whole-picture",
    "title": "The control game: the whole picture",
    "number": "8",
    "level": 1
  },
  {
    "id": "the-control-game-the-whole-picture-1",
    "title": "The control game: the whole picture",
    "number": "8.1",
    "level": 2
  }
],
};
