import type { ExternalResource } from "@/lib/content/types";

// Placeholder resource hub entries. URLs are example.com stand-ins to be
// replaced with real links. `coveredHere: false` marks background we point to
// but deliberately do not teach (e.g. ML fundamentals).
export const resources: ExternalResource[] = [
  {
    id: "res-1",
    title: "Lorem ipsum: an introduction to alignment",
    url: "https://example.com/alignment-intro",
    type: "blog",
    topics: ["alignment", "risk"],
    level: "intro",
    author: "Placeholder Author",
    note: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    coveredHere: true,
  },
  {
    id: "res-2",
    title: "Consectetur adipiscing: a survey paper",
    url: "https://example.com/survey",
    type: "paper",
    topics: ["alignment", "interpretability"],
    level: "intermediate",
    author: "Placeholder et al.",
    note: "Sed do eiusmod tempor incididunt ut labore.",
    coveredHere: true,
  },
  {
    id: "res-3",
    title: "Threat modeling fundamentals (video)",
    url: "https://example.com/threat-modeling",
    type: "video",
    topics: ["threat-modeling", "risk"],
    level: "intro",
    note: "Ut enim ad minim veniam, quis nostrud.",
    coveredHere: true,
  },
  {
    id: "res-4",
    title: "Robustness and evaluations: a short course",
    url: "https://example.com/evals-course",
    type: "course",
    topics: ["robustness", "evals"],
    level: "advanced",
    note: "Duis aute irure dolor in reprehenderit.",
    coveredHere: true,
  },
  {
    id: "res-5",
    title: "Introduction to AI governance",
    url: "https://example.com/governance-intro",
    type: "blog",
    topics: ["governance", "policy"],
    level: "intro",
    note: "Excepteur sint occaecat cupidatat non proident.",
    coveredHere: true,
  },
  {
    id: "res-6",
    title: "Policy instruments handbook",
    url: "https://example.com/policy-handbook",
    type: "book",
    topics: ["policy", "governance"],
    level: "intermediate",
    note: "Sunt in culpa qui officia deserunt mollit.",
    coveredHere: true,
  },
  {
    id: "res-7",
    title: "Interactive: explore a toy model",
    url: "https://example.com/toy-model",
    type: "interactive",
    topics: ["interpretability", "alignment"],
    level: "intermediate",
    note: "Nemo enim ipsam voluptatem quia voluptas.",
    coveredHere: true,
  },
  {
    id: "res-8",
    title: "Machine learning fundamentals (prerequisite background)",
    url: "https://example.com/ml-fundamentals",
    type: "course",
    topics: ["ml-background"],
    level: "intro",
    note: "We don't teach ML basics here — this is the background we assume. Lorem ipsum dolor sit amet.",
    coveredHere: false,
  },
  {
    id: "res-9",
    title: "Mathematics for ML (prerequisite background)",
    url: "https://example.com/math-for-ml",
    type: "course",
    topics: ["ml-background"],
    level: "intro",
    note: "Linear algebra, probability, and calculus refreshers. Not covered in Tracks.",
    coveredHere: false,
  },
];
