/**
 * Precompute reader documents at authoring time.
 *
 * For each reader in src/content/readers.data.ts this stitches its lessons'
 * MDX bodies into one combined document and derives a numbered section tree,
 * writing:
 *   src/content/readers/<id>.mdx          the combined MDX (imported by the page)
 *   src/content/readers/tocs.generated.ts the { readerId: ReaderTocEntry[] } map
 *
 * Run after editing a reader or any lesson it includes:
 *   npm run readers:build
 * content.test.ts fails if the committed output is stale.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { readers } from "../src/content/readers.data";
import { lessons } from "../src/content/curriculum.data";
import {
  assembleReaderMdx,
  buildReaderToc,
  transformLessonToSection,
} from "../src/lib/readers/generate";
import type { ReaderTocEntry } from "../src/lib/content/types";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const LESSONS_DIR = join(ROOT, "src/content/lessons");
const OUT_DIR = join(ROOT, "src/content/readers");

const lessonById = new Map(lessons.map((l) => [l.id, l]));

export interface BuiltReader {
  id: string;
  mdx: string;
  toc: ReaderTocEntry[];
}

/** Generate every reader's combined MDX + TOC from the on-disk lesson files. */
export function buildReaders(): BuiltReader[] {
  return readers.map((reader) => {
    const sections = reader.lessonIds.map((lessonId) => {
      const lesson = lessonById.get(lessonId);
      if (!lesson) throw new Error(`reader ${reader.id}: unknown lesson ${lessonId}`);
      const raw = readFileSync(join(LESSONS_DIR, `${lesson.contentRef}.mdx`), "utf8");
      return transformLessonToSection(lesson.title, raw);
    });
    const mdx = assembleReaderMdx(sections);
    return { id: reader.id, mdx, toc: buildReaderToc(mdx) };
  });
}

/** Serialize the TOC map to a committed, typed module. */
export function renderTocModule(built: BuiltReader[]): string {
  const entries = built
    .map((b) => `  ${JSON.stringify(b.id)}: ${JSON.stringify(b.toc, null, 2)},`)
    .join("\n");
  return [
    "// GENERATED by scripts/build-readers.ts — do not edit by hand.",
    "// Run `npm run readers:build` to regenerate.",
    'import type { ReaderTocEntry } from "@/lib/content/types";',
    "",
    "export const readerTocs: Record<string, ReaderTocEntry[]> = {",
    entries,
    "};",
    "",
  ].join("\n");
}

function main(): void {
  mkdirSync(OUT_DIR, { recursive: true });
  const built = buildReaders();
  for (const { id, mdx } of built) {
    writeFileSync(join(OUT_DIR, `${id}.mdx`), mdx);
    const headings = mdx.split("\n").filter((l) => /^#{1,6}\s/.test(l)).length;
    console.log(`✓ ${id}: ${mdx.length} chars, ${headings} headings`);
  }
  writeFileSync(join(OUT_DIR, "tocs.generated.ts"), renderTocModule(built));
  console.log(`✓ wrote tocs.generated.ts (${built.length} readers)`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
